INSERT INTO `diseases` (`disease_name`, `scientific_name`, `description`, `prevention`, `symptoms`, `treatment_recommendations`, `image_url_example`, `gemini_informasi_detail`, `gemini_solusi_penyembuhan`, `gemini_rekomendasi_produk_json`, `disease_name_id`, `description_id`, `prevention_id`, `symptoms_id`, `treatment_recommendations_id`, `disease_name_en`, `description_en`, `prevention_en`, `symptoms_en`, `treatment_recommendations_en`) VALUES
('Bacterial Leaf Blight', 'Xanthomonas oryzae pv. oryzae', 'Penyakit Hawar Daun Bakteri (BLB) adalah penyakit padi yang disebabkan oleh bakteri. Gejala meliputi lesi berair pada daun.', 'Gunakan varietas tahan, hindari pupuk N berlebihan.', 'Lesi berair di tepi daun, memanjang, menjadi kuning atau putih kecoklatan.', 'Penggunaan varietas tahan, sanitasi, dan bakterisida.', 'https://example.com/bacterial_leaf_blight.jpg', '{
  "informasi_detail": "Penyakit Hawar Daun Bakteri (BLB) disebabkan oleh bakteri *Xanthomonas oryzae pv. oryzae*. Penyakit ini merupakan salah satu penyakit utama pada padi yang dapat menyebabkan kehilangan hasil yang signifikan. Gejala awal biasanya muncul sebagai lesi berair atau keabu-abuan di tepi daun, yang kemudian memanjang dan membentuk garis kuning atau putih kecoklatan. Pada stadium lanjut, lesi dapat menyebar ke seluruh daun, menyebabkan daun mengering dan mati. Kondisi cuaca hangat dan lembap, terutama setelah hujan atau angin kencang, sangat mendukung perkembangan penyakit ini. Bakteri masuk melalui luka pada daun atau stomata.",
  "symptoms": "Gejala awal berupa garis-garis berair di tepi daun yang kemudian menjadi kuning atau putih kecoklatan. Daun mengering dari ujung dan bisa menyebar ke seluruh helaian daun. Pada kasus parah, seluruh tanaman bisa layu dan mati."
}', '{
  "solusi_penyembuhan": "Untuk mengendalikan Hawar Daun Bakteri, direkomendasikan penggunaan varietas padi yang tahan terhadap penyakit ini. Praktik sanitasi lahan yang baik, seperti membersihkan sisa-sisa tanaman terinfeksi setelah panen, sangat penting. Hindari pemupukan nitrogen berlebihan karena dapat memicu perkembangan penyakit. Pengaturan jarak tanam yang optimal dan drainase yang baik juga membantu mengurangi kelembaban di sekitar tanaman. Jika infeksi sudah parah, penggunaan bakterisida dapat dipertimbangkan, namun harus sesuai dosis dan anjuran."
}', '[
  {"nama_produk": "Varietas Padi Tahan BLB", "deskripsi_singkat": "Benih padi varietas unggul yang memiliki resistensi terhadap serangan Hawar Daun Bakteri."},
  {"nama_produk": "Bakterisida Pertanian", "deskripsi_singkat": "Produk pengendali bakteri khusus untuk tanaman padi, digunakan sesuai anjuran dan dosis yang tepat."},
  {"nama_produk": "Pupuk Kalium", "deskripsi_singkat": "Memperkuat jaringan tanaman dan meningkatkan ketahanan terhadap penyakit, gunakan secukupnya sesuai kebutuhan tanaman."}
]', 'Bacterial Leaf Blight', 'Penyakit Hawar Daun Bakteri (BLB) adalah penyakit padi yang disebabkan oleh bakteri. Gejala meliputi lesi berair pada daun.', 'Gunakan varietas tahan, hindari pupuk N berlebihan.', 'Lesi berair di tepi daun, memanjang, menjadi kuning atau putih kecoklatan.', 'Penggunaan varietas tahan, sanitasi, dan bakterisida.', 'Bacterial Leaf Blight', 'Bacterial Leaf Blight (BLB) is a rice disease caused by bacteria. Symptoms include water-soaked lesions on leaves.', 'Use resistant varieties, avoid excessive N fertilizer.', 'Water-soaked lesions on leaf margins, extending, turning yellowish-white or grayish-brown.', 'Use of resistant varieties, sanitation, and bactericides.'),

('Brown Spot', 'Bipolaris oryzae', 'Penyakit Bercak Coklat disebabkan oleh jamur *Bipolaris oryzae*. Menyebabkan bercak oval berwarna coklat pada daun.', 'Gunakan benih sehat, drainase baik, pupuk berimbang.', 'Bercak oval atau bulat, berwarna coklat dengan titik kuning di tengah, pada daun tua.', 'Penggunaan benih sehat, rotasi tanaman, dan fungisida.', 'https://example.com/brown_spot.jpg', '{
  "informasi_detail": "Penyakit Bercak Coklat disebabkan oleh jamur *Bipolaris oryzae*. Penyakit ini umumnya menyerang tanaman padi pada tahap pembibitan hingga fase panen. Gejala khasnya adalah munculnya bercak-bercak oval atau bulat berwarna coklat pada daun, seringkali dengan pusat lebih gelap dan lingkaran kuning di sekelilingnya. Pada serangan parah, bercak dapat menyatu, menyebabkan daun menguning dan mati. Penyakit ini juga dapat menyerang gabah, menyebabkan perubahan warna dan mengurangi kualitas serta kuantitas hasil panen. Kondisi lingkungan yang lembap dan suhu tinggi, serta kekurangan nutrisi (terutama kalium), memperburuk penyakit.",
  "symptoms": "Bercak oval atau bulat, berwarna coklat dengan titik kuning atau abu-abu di tengahnya, sering dikelilingi oleh lingkaran kuning. Terutama pada daun tua, dapat menyebar ke gabah."
}', '{
  "solusi_penyembuhan": "Pengendalian Bercak Coklat meliputi penggunaan benih sehat yang bebas patogen dan perlakuan benih dengan fungisida. Pemupukan yang seimbang, terutama dengan kalium yang cukup, dapat meningkatkan ketahanan tanaman. Rotasi tanaman dengan tanaman bukan inang membantu mengurangi sumber inokulum. Drainase lahan yang baik dan pengaturan jarak tanam yang tidak terlalu rapat juga penting untuk mengurangi kelembapan. Jika diperlukan, aplikasi fungisida dapat dilakukan sesuai dengan anjuran dan tingkat keparahan serangan."
}', '[
  {"nama_produk": "Benih Padi Sehat", "deskripsi_singkat": "Benih berkualitas tinggi yang bebas dari patogen jamur penyebab bercak coklat."},
  {"nama_produk": "Fungisida Sistemik", "deskripsi_singkat": "Produk fungisida untuk mengendalikan infeksi jamur pada daun padi, digunakan sesuai petunjuk."},
  {"nama_produk": "Pupuk Mikro", "deskripsi_singkat": "Suplemen nutrisi untuk meningkatkan vitalitas dan ketahanan alami tanaman terhadap penyakit."}
]', 'Brown Spot', 'Penyakit Bercak Coklat disebabkan oleh jamur *Bipolaris oryzae*. Menyebabkan bercak oval berwarna coklat pada daun.', 'Gunakan benih sehat, drainase baik, pupuk berimbang.', 'Bercak oval atau bulat, berwarna coklat dengan titik kuning di tengah, pada daun tua.', 'Penggunaan benih sehat, rotasi tanaman, dan fungisida.', 'Brown Spot', 'Brown Spot disease is caused by the fungus *Bipolaris oryzae*. It causes oval, brown spots on leaves.', 'Use healthy seeds, good drainage, balanced fertilization.', 'Oval or round, brown spots with a yellowish dot in the center, on older leaves.', 'Use of healthy seeds, crop rotation, and fungicides.'),

('Leaf Blast', 'Magnaporthe oryzae', 'Penyakit Blas adalah penyakit jamur yang serius, disebabkan oleh *Magnaporthe oryzae*. Dapat menyerang semua bagian tanaman.', 'Gunakan varietas tahan, hindari pupuk N berlebihan, semprot fungisida.', 'Lesi berbentuk belah ketupat dengan pusat keabu-abuan dan tepi coklat gelap pada daun, bisa juga pada buku dan malai.', 'Varietas tahan, manajemen nitrogen, fungisida, dan perlakuan benih.', 'https://example.com/leaf_blast.jpg', '{
  "informasi_detail": "Penyakit Blas, disebabkan oleh jamur *Magnaporthe oryzae*, adalah salah satu penyakit paling merusak pada padi. Jamur ini dapat menyerang tanaman pada semua tahap pertumbuhan dan pada semua bagian tanaman: daun, buku, leher malai, dan gabah. Gejala khas pada daun adalah lesi berbentuk belah ketupat (diamond-shaped) dengan pusat keabu-abuan atau putih dan tepi berwarna coklat kemerahan gelap. Lesi ini dapat membesar dan menyatu, mengurangi fotosintesis. Pada leher malai, infeksi dapat menyebabkan malai patah (neck blast), yang mengakibatkan gabah hampa atau pengisian gabah yang buruk. Kondisi dingin, lembap, dan berkabut, serta pemupukan nitrogen yang berlebihan, sangat mendukung penyebaran penyakit.",
  "symptoms": "Lesi berbentuk belah ketupat dengan pusat abu-abu dan tepi coklat gelap pada daun. Infeksi pada leher malai dapat menyebabkan patahnya leher malai. Pada buku, dapat menyebabkan pembusukan."
}', '{
  "solusi_penyembuhan": "Pengendalian penyakit Blas melibatkan penggunaan varietas padi yang tahan, meskipun ketahanan ini bisa saja rusak seiring waktu. Hindari pemupukan nitrogen yang berlebihan, karena nitrogen tinggi membuat tanaman lebih rentan. Manajemen air yang baik juga penting. Perlakuan benih dengan fungisida dapat melindungi bibit muda. Jika serangan sudah terjadi, aplikasi fungisida daun yang tepat sangat diperlukan, terutama pada fase kritis seperti pembentukan malai. Penanaman serentak di suatu area juga dapat membantu mengurangi penyebaran penyakit."
}', '[
  {"nama_produk": "Varietas Padi Tahan Blas", "deskripsi_singkat": "Benih padi varietas unggul yang memiliki ketahanan alami terhadap penyakit Blas."},
  {"nama_produk": "Fungisida Spesifik Blas", "deskripsi_singkat": "Produk fungisida yang efektif untuk mengendalikan jamur penyebab penyakit Blas, aplikasi sesuai jadwal dan dosis."},
  {"nama_produk": "Pupuk Silika", "deskripsi_singkat": "Memperkuat dinding sel tanaman padi, meningkatkan ketahanan fisik terhadap penetrasi jamur Blas."}
]', 'Leaf Blast', 'Penyakit Blas adalah penyakit jamur yang serius, disebabkan oleh *Magnaporthe oryzae*. Dapat menyerang semua bagian tanaman.', 'Gunakan varietas tahan, hindari pupuk N berlebihan, semprot fungisida.', 'Lesi berbentuk belah ketupat dengan pusat keabu-abuan dan tepi coklat gelap pada daun, bisa juga pada buku dan malai.', 'Varietas tahan, manajemen nitrogen, fungisida, dan perlakuan benih.', 'Leaf Blast', 'Blast disease is a serious fungal disease caused by *Magnaporthe oryzae*. It can affect all parts of the plant.', 'Use resistant varieties, avoid excessive N fertilizer, spray fungicides.', 'Diamond-shaped lesions with grayish centers and dark brown margins on leaves, also on nodes and panicles.', 'Resistant varieties, nitrogen management, fungicides, and seed treatment.'),

('Leaf Scald', 'Monographella albescens', 'Penyakit Hawar Daun (Leaf Scald) disebabkan oleh jamur *Monographella albescens*. Gejala berupa bercak coklat keabu-abuan yang membesar.', 'Sanitasi, varietas tahan, dan fungisida.', 'Bercak coklat keabu-abuan di ujung atau tepi daun, membesar dan bergabung membentuk hawar.', 'Sanitasi, penggunaan varietas toleran, dan fungisida.', 'https://example.com/leaf_scald.jpg', '{
  "informasi_detail": "Penyakit Hawar Daun (Leaf Scald) disebabkan oleh jamur *Monographella albescens*. Penyakit ini seringkali muncul di daerah tropis dan subtropis, terutama pada kondisi kelembapan tinggi dan suhu hangat. Gejala awal berupa bercak keabu-abuan atau coklat kehijauan yang muncul di ujung atau tepi daun. Bercak ini kemudian membesar, menyebar ke seluruh daun, dan seringkali bergabung membentuk hawar yang luas, membuat daun terlihat seperti melepuh atau tersiram air panas (scald). Pada serangan parah, daun bisa mengering dan mati, yang berdampak pada penurunan hasil panen. Penyakit ini juga dapat menyebar ke pelepah daun.",
  "symptoms": "Bercak keabu-abuan atau coklat kehijauan di ujung atau tepi daun, membesar dan bergabung membentuk hawar besar yang menyerupai luka bakar atau melepuh."
}', '{
  "solusi_penyembuhan": "Pengendalian Hawar Daun meliputi praktik sanitasi yang baik, seperti menghilangkan sisa-sisa tanaman terinfeksi dan gulma yang dapat menjadi inang alternatif. Penggunaan varietas padi yang memiliki tingkat toleransi atau resistensi terhadap penyakit ini sangat dianjurkan. Hindari kepadatan tanaman yang berlebihan untuk memastikan sirkulasi udara yang baik dan mengurangi kelembaban. Jika penyakit sudah menyebar luas, aplikasi fungisida yang tepat dapat membantu mengendalikan penyebaran, namun harus sesuai dengan dosis dan jadwal yang direkomendasikan."
}', '[
  {"nama_produk": "Varietas Padi Toleran Leaf Scald", "deskripsi_singkat": "Benih padi dengan tingkat toleransi tinggi terhadap infeksi jamur penyebab Hawar Daun."},
  {"nama_produk": "Fungisida Protektif", "deskripsi_singkat": "Produk fungisida yang memberikan perlindungan pada permukaan daun untuk mencegah penetrasi jamur Hawar Daun."},
  {"nama_produk": "Pupuk Organik", "deskripsi_singkat": "Meningkatkan kesehatan tanah dan vitalitas tanaman, sehingga lebih tahan terhadap stres dan penyakit."}
]', 'Leaf Scald', 'Penyakit Hawar Daun (Leaf Scald) disebabkan oleh jamur *Monographella albescens*. Gejala berupa bercak coklat keabu-abuan yang membesar.', 'Sanitasi, varietas tahan, dan fungisida.', 'Bercak coklat keabu-abuan di ujung atau tepi daun, membesar dan bergabung membentuk hawar.', 'Sanitasi, penggunaan varietas toleran, dan fungisida.', 'Leaf Scald', 'Leaf Scald disease is caused by the fungus *Monographella albescens*. Symptoms include enlarging grayish-brown spots on leaves.', 'Sanitation, resistant varieties, and fungicides.', 'Grayish-brown spots on leaf tips or margins, enlarging and coalescing to form scalds.', 'Sanitation, use of tolerant varieties, and fungicides.'),

('Narrow Brown Leaf Spot', 'Cercospora oryzae', 'Penyakit Bercak Daun Coklat Sempit disebabkan oleh jamur *Cercospora oryzae*. Menyebabkan bercak coklat tipis dan memanjang.', 'Varietas tahan, pupuk berimbang, dan fungisida.', 'Bercak coklat sempit, memanjang, sering dengan lingkaran kuning. Terutama pada daun tua.', 'Penggunaan varietas tahan, manajemen nutrisi, dan fungisida.', 'https://example.com/narrow_brown_leaf_spot.jpg', '{
  "informasi_detail": "Penyakit Bercak Daun Coklat Sempit (Narrow Brown Leaf Spot) disebabkan oleh jamur *Cercospora oryzae*. Penyakit ini umumnya menyerang tanaman padi pada fase pertumbuhan vegetatif akhir hingga fase pengisian gabah. Gejala khasnya adalah munculnya bercak-bercak coklat sempit, memanjang, seringkali dikelilingi oleh halo kuning, terutama pada daun tua. Bercak ini bisa sangat kecil dan banyak, memberikan tampilan daun yang berkarat. Pada kasus parah, bercak dapat menyatu dan menyebabkan kematian daun prematur, yang berdampak pada fotosintesis dan pengisian gabah. Kondisi lingkungan yang lembap dan kurangnya nutrisi (terutama kalium) dapat memperparah penyakit.",
  "symptoms": "Bercak coklat sempit dan memanjang, sering dikelilingi lingkaran kuning, terutama pada daun tua. Memberikan kesan daun berkarat."
}', '{
  "solusi_penyembuhan": "Pengendalian Bercak Daun Coklat Sempit meliputi penggunaan varietas padi yang tahan atau toleran terhadap penyakit ini. Pemupukan yang seimbang, khususnya memastikan ketersediaan kalium yang cukup, dapat meningkatkan ketahanan tanaman. Sanitasi lahan setelah panen untuk mengurangi inokulum jamur juga penting. Pengaturan jarak tanam yang optimal membantu sirkulasi udara dan mengurangi kelembapan. Aplikasi fungisida dapat dipertimbangkan jika penyakit sudah menyebar luas, sesuai dengan anjuran dan dosis yang direkomendasikan."
}', '[
  {"nama_produk": "Varietas Padi Tahan NBS", "deskripsi_singkat": "Benih padi varietas unggul yang memiliki resistensi terhadap serangan jamur penyebab Bercak Coklat Sempit."},
  {"nama_produk": "Pupuk Kalium Tinggi", "deskripsi_singkat": "Pupuk yang kaya kalium untuk meningkatkan ketahanan tanaman dan mengurangi kerentanan terhadap penyakit."},
  {"nama_produk": "Fungisida Kontak/Sistemik", "deskripsi_singkat": "Produk fungisida untuk mengendalikan infeksi jamur pada daun padi, digunakan sesuai petunjuk."}
]', 'Narrow Brown Leaf Spot', 'Penyakit Bercak Daun Coklat Sempit disebabkan oleh jamur *Cercospora oryzae*. Menyebabkan bercak coklat tipis dan memanjang.', 'Varietas tahan, pupuk berimbang, dan fungisida.', 'Bercak coklat sempit, memanjang, sering dengan lingkaran kuning. Terutama pada daun tua.', 'Penggunaan varietas tahan, manajemen nutrisi, dan fungisida.', 'Narrow Brown Leaf Spot', 'Narrow Brown Leaf Spot disease is caused by the fungus *Cercospora oryzae*. It causes thin, elongated brown spots on leaves.', 'Resistant varieties, balanced fertilization, and fungicides.', 'Narrow, elongated brown spots, often with a yellow halo. Primarily on older leaves.', 'Use of resistant varieties, nutrient management, and fungicides.'),

('Rice Hispa', 'Dicladispa armigera', 'Hama Hispa (Dicladispa armigera) adalah kumbang kecil yang menyerang daun padi. Larva membuat terowongan di dalam daun.', 'Manajemen air, insektisida, dan musuh alami.', 'Garis putih panjang karena larva memakan jaringan daun di antara epidermis, daun menguning atau kering.', 'Pengendalian hama terpadu, musuh alami, dan insektisida.', 'https://example.com/rice_hispa.jpg', '{
  "informasi_detail": "Hama Hispa, atau kumbang daun padi (*Dicladispa armigera*), adalah serangga hama yang dapat menyebabkan kerusakan signifikan pada tanaman padi. Baik kumbang dewasa maupun larvanya menyerang daun padi. Kumbang dewasa mengikis permukaan atas daun, meninggalkan garis-garis putih paralel. Namun, kerusakan yang lebih parah disebabkan oleh larva, yang membuat terowongan dan memakan jaringan di antara epidermis daun (mining). Aktivitas makan ini menghasilkan garis-garis putih transparan yang panjang pada daun, yang kemudian dapat menyebabkan daun menguning, mengering, dan mati. Serangan parah dapat mengurangi luas permukaan daun yang berfotosintesis, menghambat pertumbuhan tanaman dan menurunkan hasil panen.",
  "symptoms": "Kumbang dewasa mengikis permukaan daun. Larva membuat terowongan di dalam daun, meninggalkan garis-garis putih panjang yang kemudian menyebabkan daun menguning dan mengering."
}', '{
  "solusi_penyembuhan": "Pengendalian hama Hispa dapat dilakukan melalui beberapa cara. Pengelolaan air yang baik di sawah dapat membantu mengurangi populasi hama. Penggunaan musuh alami, seperti parasitoid telur dan predator, sangat dianjurkan sebagai bagian dari pendekatan Pengendalian Hama Terpadu (PHT). Jika populasi hama sangat tinggi, aplikasi insektisida dapat dipertimbangkan, namun harus dipilih yang ramah lingkungan dan sesuai dosis. Penanaman varietas tahan atau toleran juga merupakan strategi penting."
}', '[
  {"nama_produk": "Insektisida Nabati", "deskripsi_singkat": "Insektisida alami yang efektif mengendalikan hama Hispa tanpa merusak lingkungan atau musuh alami."},
  {"nama_produk": "Pestisida Sistemik", "deskripsi_singkat": "Pestisida yang diserap tanaman dan melindungi dari serangan hama pengunyah daun seperti Hispa."},
  {"nama_produk": "Perangkap Feromon", "deskripsi_singkat": "Alat perangkap untuk memantau dan mengurangi populasi kumbang Hispa dewasa secara massal."}
]', 'Rice Hispa', 'Hama Hispa (Dicladispa armigera) adalah kumbang kecil yang menyerang daun padi. Larva membuat terowongan di dalam daun.', 'Manajemen air, insektisida, dan musuh alami.', 'Garis putih panjang karena larva memakan jaringan daun di antara epidermis, daun menguning atau kering.', 'Pengendalian hama terpadu, musuh alami, dan insektisida.', 'Rice Hispa', 'Rice Hispa (Dicladispa armigera) is a small beetle pest that attacks rice leaves. Larvae tunnel inside the leaves.', 'Water management, insecticides, and natural enemies.', 'Long white streaks as larvae feed on leaf tissue between epidermis, leaves turn yellow or dry.', 'Integrated pest management, natural enemies, and insecticides.'),

('Sheath Blight', 'Rhizoctonia solani', 'Penyakit Hawar Pelepah Daun disebabkan oleh jamur *Rhizoctonia solani*. Menyerang pelepah daun dekat permukaan air.', 'Drainase baik, jarak tanam optimal, fungisida.', 'Bercak oval atau elips berwarna hijau keabu-abuan pada pelepah daun, seringkali dengan batas coklat.', 'Manajemen kelembaban, jarak tanam, dan fungisida.', 'https://example.com/sheath_blight.jpg', '{
  "informasi_detail": "Penyakit Hawar Pelepah Daun (Sheath Blight) disebabkan oleh jamur *Rhizoctonia solani*. Penyakit ini umumnya menyerang pelepah daun padi yang berada dekat dengan permukaan air. Gejala awal berupa bercak oval atau elips berwarna hijau keabu-abuan atau abu-abu kehijauan, yang kemudian membesar dan meluas, seringkali dengan batas berwarna coklat kemerahan atau coklat gelap. Bercak-bercak ini dapat menyebar ke atas, ke helaian daun dan malai, menyebabkan kerusakan jaringan yang parah. Kondisi kelembapan tinggi, suhu hangat, dan kepadatan tanaman yang tinggi sangat mendukung perkembangan penyakit ini, yang dapat mengurangi pengisian gabah dan menyebabkan kehilangan hasil.",
  "symptoms": "Bercak oval atau elips berwarna hijau keabu-abuan pada pelepah daun dekat permukaan air, membesar dan menyebar ke atas."
}', '{
  "solusi_penyembuhan": "Pengendalian Hawar Pelepah Daun dapat dilakukan dengan mengatur jarak tanam yang optimal untuk memastikan sirkulasi udara yang baik dan mengurangi kelembapan di kanopi tanaman. Drainase sawah yang baik secara berkala juga membantu mengurangi kelembapan tanah dan area sekitar pelepah. Hindari pemupukan nitrogen yang berlebihan. Penggunaan varietas yang toleran atau memiliki ketahanan parsial dapat membantu. Jika infeksi sudah parah, aplikasi fungisida yang tepat, terutama yang menargetkan bagian bawah tanaman, diperlukan sesuai dengan anjuran dan dosis."
}', '[
  {"nama_produk": "Fungisida Sistemik Kontak", "deskripsi_singkat": "Fungisida yang bekerja secara sistemik dan kontak untuk mengendalikan jamur *Rhizoctonia solani*."},
  {"nama_produk": "Varietas Padi Toleran", "deskripsi_singkat": "Benih padi dengan karakteristik toleran terhadap serangan Hawar Pelepah Daun."},
  {"nama_produk": "Pupuk Kalsium", "deskripsi_singkat": "Memperkuat dinding sel tanaman, meningkatkan ketahanan terhadap infeksi jamur."}
]', 'Sheath Blight', 'Penyakit Hawar Pelepah Daun disebabkan oleh jamur *Rhizoctonia solani*. Menyerang pelepah daun dekat permukaan air.', 'Drainase baik, jarak tanam optimal, fungisida.', 'Bercak oval atau elips berwarna hijau keabu-abuan pada pelepah daun, seringkali dengan batas coklat.', 'Manajemen kelembaban, jarak tanam, dan fungisida.', 'Sheath Blight', 'Sheath Blight disease is caused by the fungus *Rhizoctonia solani*. It attacks leaf sheaths near the water surface.', 'Good drainage, optimal planting density, fungicides.', 'Oval or elliptical grayish-green spots on leaf sheaths, often with brown borders.', 'Moisture management, planting density, and fungicides.');
